import type { Project, Certificate } from "@/types/database";

export const MOCK_PROJECTS: Project[] = [
  {
    id: "1",
    slug: "ekiportfolio",
    title: "Eki Portfolio",
    description: "Personal portfolio web — a living dashboard combining CV, activity tracking, and mini-apps.",
    long_description: "This very website. Built with Next.js 16, TypeScript, Tailwind CSS, shadcn/ui, and Supabase. Features bilingual support, Catppuccin theming, real-time widgets, and a 3D asset viewer.",
    thumbnail_url: null,
    screenshots: [],
    tech_stack: ["Next.js", "TypeScript", "Tailwind CSS", "Supabase", "Framer Motion"],
    website_url: "#",
    source_url: "https://github.com/NeiaKI/Portfolio-Web",
    is_featured: true,
    created_at: "2026-05-16T00:00:00Z",
  },
  {
    id: "2",
    slug: "blender-glb-assets",
    title: "Gamma Game Assets",
    description: "3D asset pack for game developers — low-poly GLB models optimized for real-time rendering.",
    long_description: "A collection of hand-crafted 3D assets made in Blender, exported as GLB with Draco compression. Covers props, environment, and character assets for indie game projects.",
    thumbnail_url: null,
    screenshots: [],
    tech_stack: ["Blender", "Three.js", "GLTF", "Draco"],
    website_url: null,
    source_url: null,
    is_featured: true,
    created_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "3",
    slug: "arch-dotfiles",
    title: "EkiArch Dotfiles",
    description: "Hyprland-based Arch Linux rice — dotfiles for a complete, reproducible desktop setup.",
    long_description: "Personal dotfiles for EkiArch — Hyprland WM, Waybar, Alacritty, and more. Fully documented for easy reproduction on any Arch Linux installation.",
    thumbnail_url: null,
    screenshots: [],
    tech_stack: ["Arch Linux", "Hyprland", "Waybar", "Bash", "Nix"],
    website_url: null,
    source_url: "https://github.com/nekidev",
    is_featured: false,
    created_at: "2025-11-01T00:00:00Z",
  },
  {
    id: "4",
    slug: "rest-api-go",
    title: "Go REST API Boilerplate",
    description: "Production-ready REST API starter built with Go, featuring JWT auth, PostgreSQL, and Docker.",
    long_description: "A boilerplate for building REST APIs in Go. Includes JWT authentication, role-based access control, PostgreSQL with migrations, structured logging, and Docker Compose setup.",
    thumbnail_url: null,
    screenshots: [],
    tech_stack: ["Go", "PostgreSQL", "Docker", "JWT", "REST API"],
    website_url: null,
    source_url: "https://github.com/nekidev",
    is_featured: false,
    created_at: "2025-08-15T00:00:00Z",
  },
  {
    id: "5",
    slug: "linux-command-quiz",
    title: "Linux Command Quiz",
    description: "Interactive quiz app for learning Linux commands — supports Bash, vim, and system administration topics.",
    long_description: "A web-based quiz for learning Linux commands. Covers Bash scripting, file system navigation, process management, and vim. Built as a tool for the EkiArch community.",
    thumbnail_url: null,
    screenshots: [],
    tech_stack: ["Next.js", "TypeScript", "Tailwind CSS"],
    website_url: "#",
    source_url: "https://github.com/nekidev",
    is_featured: false,
    created_at: "2025-06-01T00:00:00Z",
  },
];

export const MOCK_CERTIFICATES: Certificate[] = [
  {
    id: "1",
    title: "AWS Certified Cloud Practitioner",
    issuer: "Amazon Web Services",
    thumbnail_url: null,
    certificate_url: "#",
    issued_date: "2025-09-01",
  },
  {
    id: "2",
    title: "Next.js Advanced Patterns",
    issuer: "Vercel",
    thumbnail_url: null,
    certificate_url: "#",
    issued_date: "2025-07-15",
  },
  {
    id: "3",
    title: "TypeScript Deep Dive",
    issuer: "Udemy",
    thumbnail_url: null,
    certificate_url: "#",
    issued_date: "2025-04-20",
  },
  {
    id: "4",
    title: "Docker & Kubernetes Fundamentals",
    issuer: "Linux Foundation",
    thumbnail_url: null,
    certificate_url: "#",
    issued_date: "2024-12-01",
  },
  {
    id: "5",
    title: "Blender for Game Artists",
    issuer: "CG Cookie",
    thumbnail_url: null,
    certificate_url: "#",
    issued_date: "2024-08-10",
  },
  {
    id: "6",
    title: "PostgreSQL for Developers",
    issuer: "pganalyze",
    thumbnail_url: null,
    certificate_url: "#",
    issued_date: "2024-05-22",
  },
];
